version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kwetter_docker_db'
      MYSQL_USER: 'Kwetter'
      MYSQL_PASSWORD: 'kwetter'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    expose:
      - 3306

  kwetter_api:
    image: ronindebeek/kwetter_api:latest
    ports:
      - 8080:8080
    links:
      - database
      
  kwetter_angular:
    image: ronindebeek/kwetter_angular:latest
    ports:
      - 4200:4200