version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'kwetter_docker_db'
      MYSQL_USER: 'Kwetter'
      MYSQL_PASSWORD: 'kwetter'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    expose:
      - 3306
      
  payara:
    image: payara/server-full:latest
    ports:
      - 4848:4848
      - 8080:8080
      - 8181:8181
    volumes:
      - ./kwetter_api/target:/opt/payara/deployments
    depends_on:
      - "database"
          

      