version: 2.1

workflows:
    version: 2.1
    build-test-deploy:
        jobs:
            - checkout

            - dependancies_backend:
                requires:
                    - checkout  
            - dependancies_frontend:
                requires:
                    - checkout

            - sonarqube:
                requires:
                    - checkout                   
         
            - build_backend:
                requires:
                    - dependancies_backend
            - build_frontend:
                requires:
                    - dependancies_frontend

            - test_backend:
                requires:
                    - build_backend
            - lint_frontend:
                requires:
                    - build_frontend
            - test_frontend:
                requires:
                    - build_frontend

            - docker_backend:
                context:
                    kwetter
                requires:
                    - sonarqube
                    - test_backend
            - docker_frontend:
                context:
                    kwetter
                requires:
                    - sonarqube
                    - lint_frontend
                    - test_frontend                                      

executors:
    python:
        docker:
            - image: python
    java:
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            MAVEN_OPTS: -Xmx3200m
            SOURCE_PATH: kwetter_backend
    node:
        docker:
            - image: circleci/node:10.15.3
        environment:
            SOURCE_PATH: kwetter_angular

commands:
    attach_workspace_:
        steps:
            - attach_workspace:
                at: .

    persist_workspace_:
        steps:
            - persist_to_workspace:
                root: .
                paths:
                    - kwetter_backend
                    - kwetter_angular

    persist_workspace_sonar:
        steps:
            - persist_to_workspace:
                root: .
                paths:
                    - sonar-scanner-3.3.0.1492-linux

    run_docker:
        parameters:
            user:
                type: string
                default: .
            pass:
                type: string
                default: .
            source:
                type: string
                default: .                                
        steps:
            - run:
                name: Docker Login Echo
                command: echo docker login -u << parameters.user >> -p << parameters.pass >>                
            - run:
                name: Docker Login
                command: docker login -u << parameters.user >> -p << parameters.pass >>
            - run:
                name: Docker Build
                command: docker build -t << parameters.user >>/<< parameters.source >>:$CIRCLE_BRANCH ./project/<< parameters.source >>
            - run:
                name: Docker Push
                command: docker push << parameters.user >>/<< parameters.source >>:$CIRCLE_BRANCH                                                   

jobs:
    checkout:
        executor: python
        steps:
            - checkout          
            - persist_workspace_

    sonarqube:
        executor: java
        steps:
            - attach_workspace_
            - run:
                command: |
                    mvn sonar:sonar \
                    -Dsonar.projectKey=kwetter \
                    -Dsonar.organization=ronaldvandenbroek-github \
                    -Dsonar.host.url=https://sonarcloud.io \
                    -Dsonar.login=ddbe3280d03d59f0c290db4a1cd256c9c64a6858

    dependancies_backend:
        executor: java
        steps:
            - attach_workspace_
            - run:
                name: Maven Go-Offline
                command: cd $SOURCE_PATH && mvn dependency:go-offline     
            - persist_workspace_
    
    dependancies_frontend:
        executor: node
        steps:
            - attach_workspace_
            - run:
                name: Install local dependencies
                command: cd $SOURCE_PATH && npm install
            - persist_workspace_

    build_backend:
        executor: java
        steps:
            - attach_workspace_
            - run:
                name: Build Backend
                command: cd $SOURCE_PATH && mvn install -DskipTests              
            - persist_workspace_

    build_frontend:
        executor: node
        steps:
            - attach_workspace_
            - run:
                name: Build Frontend
                command: cd $SOURCE_PATH && npm run build           
            - persist_workspace_

    test_backend:
        executor: java
        steps:
            - attach_workspace_
            - run:
                name: Test Backend
                command: cd $SOURCE_PATH && mvn surefire:test

    lint_frontend:
        executor: node
        steps:
            - attach_workspace_
            # Disabled for testing purposes
            # - run:
            #     name: Linting
            #     command: cd $SOURCE_PATH && npm run lint

    test_frontend:
        executor: node
        steps:
            - attach_workspace_
            # Disabled for testing purposes
            # - run:
            #     name: Testing
            #     command: cd $SOURCE_PATH && npm run test

    docker_backend:
        machine: true
        environment:
            SOURCE_PATH: kwetter_backend
        steps:
            - attach_workspace:
                at: project
            - run_docker:
                user: "${DOCKER_USER}"
                pass: "${DOCKER_PASS}"
                source: "${SOURCE_PATH}"

    docker_frontend:
        machine: true
        environment:
            SOURCE_PATH: kwetter_angular
        steps:
            - attach_workspace:
                at: project
            - run_docker:
                user: "${DOCKER_USER}"
                pass: "${DOCKER_PASS}"
                source: "${SOURCE_PATH}"             