# Java Maven CircleCI 2.0 configuration file

version: 2.1

workflows:
    version: 2.1
    build-test-deploy:
        jobs:
            - checkout
            - dependancies_backend:
                requires:
                    - checkout           
            - build_backend:
                requires:
                    - dependancies_backend
            - test_backend:
                requires:
                    - build_backend
executors:
    python:
        docker:
            - image: python
    java:
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            MAVEN_OPTS: -Xmx3200m
            SOURCE_PATH: kwetter_backend

commands:
    backend_attach_workspace:
        steps:
            - attach_workspace:
                at: .
    backend_persist_workspace:
        steps:
            - persist_to_workspace:
                root: .
                paths:
                    - kwetter_backend
    all_persist_workspace:
        steps:
            - persist_to_workspace:
                root: .
                paths:
                    - kwetter_backend
                    - kwetter_angular                                                 

jobs:
    checkout:
        executor: python
        steps:
            - checkout
            - all_persist_workspace

    dependancies_backend:
        executor: java
        steps:
            - backend_attach_workspace
            - run:
                name: Maven Go-Offline
                command: cd $SOURCE_PATH && mvn dependency:go-offline     
            - backend_persist_workspace

    build_backend:
        executor: java
        steps:
            - backend_attach_workspace
            - run:
                name: Build Backend
                command: cd $SOURCE_PATH && mvn install -DskipTests              
            - backend_persist_workspace

    test_backend:
        executor: java
        steps:
            - backend_attach_workspace
            - run:
                name: Test Backend
                command: cd $SOURCE_PATH && mvn surefire:test              
            - backend_persist_workspace