# Java Maven CircleCI 2.0 configuration file

version: 2.1

executors:
    java:
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            MAVEN_OPTS: -Xmx3200m
            SOURCE_PATH: kwetter_backend
  
jobs:
    dependancies_backend:
        executor: java
        steps:
            - checkout
            - run:
                name: Variable key bypass
                command: cat "$SOURCE_PATH/pom.xml" > key.txt
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "key.txt" }}
                    - v1-dependencies-
            - run:
                name: Maven Go-Offline
                command: cd $SOURCE_PATH && mvn dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "key.txt" }}            
            - persist_to_workspace:
                root: .
                paths:
                    - kwetter_backend

    build_backend:
        executor: java
        steps:
            - attach_workspace:
                at: project
            - run:
                name: Check directory
                command: ls                       
            - run:
                name: Variable key bypass
                command: cat "$SOURCE_PATH/pom.xml" > key.txt                                  
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "key.txt" }}
                    - v1-dependencies-
            - run:
                name: Build Backend
                command: cd $SOURCE_PATH && mvn install -DskipTests
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "key.txt" }}                  
            - persist_to_workspace:
                root: .
                paths:
                    - kwetter_backend

    test_backend:
        executor: java
        steps:
            - attach_workspace:
                at: project
            - run:
                name: Variable key bypass
                command: cat "$SOURCE_PATH/pom.xml" > key.txt                
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "key.txt" }}
                    - v1-dependencies-
            - run:
                name: Test Backend
                command: cd $SOURCE_PATH && mvn surefire:test
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "key.txt" }}                  
            - persist_to_workspace:
                root: .
                paths:
                    - kwetter_backend

workflows:
    version: 2.1
    build-test-deploy:
        jobs:
            - dependancies_backend           
            - build_backend:
                requires:
                    - dependancies_backend
            - test_backend:
                requires:
                    - build_backend         
                    
                    
                