# Java Maven CircleCI 2.0 configuration file

version: 2.1
  
jobs:
    backend-tests:
        docker:
            - image: circleci/openjdk:8-jdk
        working_directory: ~/repo
        environment:
            MAVEN_OPTS: -Xmx3200m
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "kwetter_backend/pom.xml" }}
                    - v1-dependencies-
            - run:
                name: Maven Go-Offline
                command: cd kwetter_backend && mvn dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "kwetter_backend/pom.xml" }}
            - run:
                name: Run Maven Tests
                command: cd kwetter_backend && mvn test
            - run:
                name: Install Sonarqube scanner
                command: |
                    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
                    unzip sonar-scanner-cli-3.3.0.1492-linux.zip
            - run:
                name: Run Sonarqube scanner
                command: |
                    cd kwetter_backend
                    export SONAR_SCANNER_OPTS="-Xmx2048m"
                    eval ./../sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=Kwetter_Backend \
                    -Dsonar.sources=. \
                    -Dsonar.sourceEncoding=US-ASCII \
                    -Dsonar.exclusions=vendor/bundle/** \
                    -Dsonar.host.url=http://28d516d2.ngrok.io \
                    -Dsonar.projectVersion=${CIRCLE_BRANCH} \

    frontend-tests:    
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "kwetter_angular/package.json" }}
                - v1-dependencies-
            - run:
                name: Install local dependencies
                command: cd kwetter_angular && npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "kwetter_angular/package.json" }}
                paths:
                    - node_modules
            #- run:
            #    name: Linting
            #    command: npm run lint
            #- run:
            #    name: Testing
            #    command: npm run test
            - run:
                name: Install Sonarqube scanner
                command: |
                    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
                    unzip sonar-scanner-cli-3.3.0.1492-linux.zip
            - run:
                name: Run Sonarqube scanner
                command: |
                    cd kwetter_angular
                    export SONAR_SCANNER_OPTS="-Xmx2048m"
                    eval ./../sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -Dsonar.projectKey=Kwetter_Angular \
                    -Dsonar.sources=. \
                    -Dsonar.sourceEncoding=US-ASCII \
                    -Dsonar.exclusions=vendor/bundle/** \
                    -Dsonar.host.url=http://28d516d2.ngrok.io \
                    -Dsonar.projectVersion=${CIRCLE_BRANCH} \
            
workflows:
  version: 2.1
  backend-frontend:
    jobs:
      - frontend-tests
      - backend-tests