version: 2.1

workflows:
    version: 2.1
    build-test-deploy:
        jobs:
            - checkout
            - dependancies_backend:
                requires:
                    - checkout           
            - build_backend:
                requires:
                    - dependancies_backend
            - test_backend:
                requires:
                    - build_backend
            - dependancies_frontend:
                requires:
                    - checkout           
            - lint_frontend:
                requires:
                    - dependancies_frontend
            - test_frontend:
                requires:
                    - dependancies_frontend

executors:
    python:
        docker:
            - image: python
    java:
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            MAVEN_OPTS: -Xmx3200m
            SOURCE_PATH: kwetter_backend
    node:
        docker:
            - image: circleci/node:10.15.3
        environment:
            SOURCE_PATH: kwetter_angular

commands:
    _attach_workspace:
        steps:
            - attach_workspace:
                at: .
    _persist_workspace:
        steps:
            - persist_to_workspace:
                root: .
                paths:
                    - kwetter_backend
                    - kwetter_angular                                                 

jobs:
    checkout:
        executor: python
        steps:
            - checkout
            - _persist_workspace

    dependancies_backend:
        executor: java
        steps:
            - _attach_workspace
            - run:
                name: Maven Go-Offline
                command: cd $SOURCE_PATH && mvn dependency:go-offline     
            - _persist_workspace
    
    dependancies_frontend:
        executor: node
        steps:
            - _attach_workspace
            - run:
                name: Install local dependencies
                command: cd $SOURCE_PATH && npm install
            - _persist_workspace

    build_backend:
        executor: java
        steps:
            - _attach_workspace
            - run:
                name: Build Backend
                command: cd $SOURCE_PATH && mvn install -DskipTests              
            - _persist_workspace

    lint_frontend:
        executor: node
        steps:
            - _attach_workspace
            - run:
                name: Linting
                command: npm run lint
            - _persist_workspace

    test_frontend:
        executor: node
        steps:
            - _attach_workspace
            - run:
                name: Testing
                command: npm run test
            - _persist_workspace

    test_backend:
        executor: java
        steps:
            - _attach_workspace
            - run:
                name: Test Backend
                command: cd $SOURCE_PATH && mvn surefire:test              
            - _persist_workspace